#!/bin/bash

set -u

# Set the ROOT environment variable, assuming that the directory structure
# mirrors that of the git repository.
ROOT="$(cd "$( dirname "${BASH_SOURCE[0]}" )/../" >/dev/null 2>&1 && pwd)"
export ROOT

###############################################################################

source ${ROOT}/tools/configuration_helpers
set_local_configuration

detect_ci
detect_os

__build_tomcat() {
    pushd "${ROOT}"
        echo "Building faceAnalyzer in $(pwd)"

        /bin/rm -rf build
        mkdir build

        pushd build > /dev/null
            if [[ $CI -eq 1 && $OSTYPE == "darwin"* ]]; then
                # On the macOS Github Actions runner, there is a problem
                # with building against OpenCV with Homebrew - something to
                # do with XCode and the Command Line Tools not playing
                # nicely together. The line below is a fix for this issue.
                sudo xcode-select -s /Library/Developer/CommandLineTools
            fi

            if [[ $OSTYPE == "linux-gnu" ]]; then
                NJOBS=$(nproc)
            else
                NJOBS=$(sysctl -n hw.ncpu)
            fi

            # On CI, we build the examples by default.
            if ! cmake ${ROOT}; then exit 1; fi

            if ! make -j $NJOBS; then exit 1; fi
        popd > /dev/null
    popd > /dev/null
}

__download_openface_models() {
    # We do not download the OpenFace models when running on a CI runner to save
    # time.
    if [[ $CI -eq 0 && ! -d ${ROOT}/data/OpenFace_models ]]; then
        if ! ${ROOT}/tools/download/OpenFace_models; then exit 1; fi
    fi
}

_install_tomcat() {
    if (( ${INSTALL_DEPENDENCIES:-1} )); then
        if ! ${ROOT}/tools/install_dependencies; then exit 1; fi
    else
        echo "INSTALL_DEPENDENCIES has been set to 0, so we skip the automatic"\
             "installation of faceAnalyzer dependencies, and assume that you have"\
             "already installed the prerequisites (either manually or using a"\
             "previous invocation of the install script.)"
    fi
    __build_tomcat
    __download_openface_models

    echo " "
    echo "Finished installing faceAnalyzer in ${ROOT}!"
    echo " "
}

_install_tomcat
exit 0
